// Re-export everything from the shared library
export {
  // Config
  config,
  type Config,
  // Validation
  validateSeverity,
  sanitizePath,
  sanitizeImageName,
  // HTTP helpers
  fetchJson,
  basicAuth,
  // Trivy
  trivyScanPath,
  trivyScanImage,
  trivyGenerateSbom,
  trivyGenerateSbomImage,
  trivyScanIac,
  trivyScanSecrets,
  trivyScanSecretsImage,
  trivyScanLicenses,
  trivyScanLicensesImage,
  trivyScanImageFull,
  trivyScanPathFull,
  // SonarQube
  sonarGetProjects,
  sonarGetIssues,
  sonarGetSecurityHotspots,
  sonarGetMetrics,
  // Dependency-Track
  dtrackGetProjects,
  dtrackGetVulnerabilities,
  dtrackGetFindings,
  dtrackGetComponents,
  uploadSbomToDtrack,
  // Gitea
  giteaGetRepos,
  giteaGetRepo,
  giteaGetBranches,
  giteaGetCommits,
  giteaCreateRepo,
  giteaMigrateRepo,
  // Drone
  droneGetRepos,
  droneGetBuilds,
  droneGetBuild,
  droneGetBuildLogs,
  droneTriggerBuild,
  // Registry
  registryGetCatalog,
  registryGetTags,
  // Combined
  securityScanAll,
  checkPlatformStatus,
  // Security Dashboard
  getSecurityDashboard,
  // Registry Scanner
  listRegistryImages,
  scanRegistry,
  // Multi-Registry
  detectRegistryType,
  configureRegistry,
  getRegistryConfig,
  listRegistryConfigs,
  removeRegistryConfig,
  getDefaultRegistry,
  clearRegistryConfigs,
  getRegistryAuth,
  scanMultipleRegistries,
  testRegistryConnection,
  // SARIF
  trivyToSarif,
  sonarToSarif,
  dtrackToSarif,
  dashboardToSarif,
  mergeSarifLogs,
  sarifToJson,
  getSarifSummary,
  uploadSarifToGitHub,
  writeSarifFile,
  // Scheduler
  parseCronExpression,
  validateCronExpression,
  describeCronExpression,
  getNextRunTime,
  getNextRunTimes,
  createSchedule,
  getSchedule,
  listSchedules,
  updateSchedule,
  deleteSchedule,
  triggerSchedule,
  getScheduleHistory,
  startScheduler,
  stopScheduler,
  saveSchedulesToFile,
  loadSchedulesFromFile,
  clearAllSchedules,
  // Remediation
  generateRemediations,
  getRemediationSummary,
  formatRemediationAsMarkdown,
  getHighPriorityRemediations,
  getSafeRemediations,
  // Compliance
  COMPLIANCE_CONTROLS,
  getComplianceFrameworks,
  getComplianceControls,
  getComplianceControl,
  mapFindingToControls,
  generateComplianceReport,
  generateComplianceHtml,
  recordComplianceTrend,
  getComplianceTrend,
  clearComplianceTrends,
  getComplianceTrendTargets,
  checkComplianceStatus,
  // OPA/Rego
  BUILTIN_POLICIES,
  listBuiltinPolicies,
  getBuiltinPolicy,
  getBuiltinPolicyInfo,
  validateRegoSyntax,
  evaluateOpaPolicy,
  evaluateMultiplePolicies,
  scanResultsToOpaInput,
  trivyResultToOpaInput,
  dashboardResultToOpaInput,
  createOpaInput,
  // Vulnerability Database
  initVulnDatabase,
  closeVulnDatabase,
  isVulnDbInitialized,
  lookupVulnerability,
  searchVulnerabilities,
  getVulnDbStats,
  annotateVulnerability,
  getVulnAnnotation,
  // Database Sync
  getTrivyDbStatus,
  downloadTrivyDb,
  syncVulnDatabase,
  getVulnDbSyncStatus,
  isOfflineScanAvailable,
  // Offline Scanner
  offlineScanImage,
  offlineScanPath,
  getOfflineScanCapabilities,
  // Redis Cache
  getRedisConfig,
  getTTLConfig,
  initRedisConnection,
  closeRedisConnection,
  isRedisConnected,
  initDistributedCaches,
  getAllCacheStats,
  clearAllCaches,
  invalidateCacheByPattern,
  getCacheHealth,
  type RedisConfig,
  type CacheStats,
  type CacheTTLConfig,
  type CacheHealthStatus,
  // Suppression Database
  initSuppressionDatabase,
  closeSuppressionDatabase,
  isSuppressionDbInitialized,
  createDbSuppression,
  getDbSuppression,
  listDbSuppressions,
  updateDbSuppression,
  deleteDbSuppression,
  logSuppressionApplication,
  getSuppressionAuditLog,
  getSuppressionDbStats,
  applyDbSuppressions,
  importSuppressionsToDb,
  exportSuppressionsFromDb,
  markExpiredSuppressions,
  type SuppressionStatus,
  type SuppressionAuditAction,
  type SuppressionAuditEntry,
  type SuppressionListOptions,
  type SuppressionDbStats,
  // Prometheus Metrics
  METRICS,
  metricsCollector,
  toPrometheusFormat,
  getMetrics,
  pushToGateway,
  deleteFromGateway,
  recordScanMetrics,
  recordCacheHit,
  recordCacheMiss,
  recordCircuitBreakerFailure,
  resetMetrics,
  getMetricsSnapshot,
  type MetricsSnapshot,
  type ScanMetrics,
  type PushgatewayConfig,
  type PushgatewayResult,
  // Scan Comparison
  extractTrivyVulnerabilities,
  compareTrivyScans,
  getScanHistory,
  resetScanHistory,
  storeTrivyScan,
  compareWithPrevious,
  storeAndCompare,
  type ScanDiffResult,
  type StoredScanRecord,
  type ScanCompareOptions,
  // SSO Configuration
  initSsoDatabase,
  closeSsoDatabase,
  isSsoDbInitialized,
  configureSamlProvider,
  configureOidcProvider,
  getSsoProvider,
  listSsoProviders,
  deleteSsoProvider,
  setSsoProviderEnabled,
  createSsoSession,
  getSsoSession,
  validateSsoSession,
  terminateSsoSession,
  terminateAllUserSessions,
  listUserSessions,
  listAllSessions,
  cleanupExpiredSessions,
  getSsoAuditEvents,
  // SSO SAML
  generateSpMetadata,
  validateSamlAssertion,
  generateSamlLogoutRequest,
  // SSO OIDC
  validateOidcToken,
  validateOidcTokenByIssuer,
  refreshOidcToken,
  getOidcUserInfo,
  // SSO Types
  type SsoProviderType,
  type SamlProviderConfig,
  type OidcProviderConfig,
  type SsoSession,
  type SsoValidationResult,
  type SsoMetadataResult,
  type SsoAuditEvent,
  type SsoDbInitResult,
  type SsoProviderSummary,
  // RBAC
  initRbacDatabase,
  closeRbacDatabase,
  isRbacDbInitialized,
  createRole,
  getRole,
  getRoleByName,
  listRoles,
  updateRole,
  deleteRole,
  listPermissions,
  grantPermissionToRole,
  revokePermissionFromRole,
  getRolePermissions,
  assignRoleToUser,
  unassignRoleFromUser,
  getUserRoles,
  checkPermission,
  listUserPermissions,
  isUserAdmin,
  getRbacAuditEvents,
  // RBAC Types
  type RbacRole,
  type RbacPermission,
  type RbacUserRole,
  type RbacCheckResult,
  type RbacAuditEvent,
  type RbacRoleWithPermissions,
  type RbacDbInitResult,
  // API Key Management
  VALID_SCOPES,
  initApiKeyDatabase,
  closeApiKeyDatabase,
  isApiKeyDbInitialized,
  createApiKey,
  getApiKey,
  listApiKeys,
  revokeApiKey,
  rotateApiKey,
  validateApiKey,
  getApiKeyAuditEvents,
  markExpiredApiKeys,
  getApiKeyStats,
  cleanupApiKeyAuditLogs,
  // API Key Types
  type ApiKeyScope,
  type ApiKeyEventType,
  type ApiKeyStatus,
  type ApiKey,
  type ApiKeyCreateOptions,
  type ApiKeyCreateResult,
  type ApiKeyDisplay,
  type ApiKeyValidationResult,
  type ApiKeyRotateResult,
  type ApiKeyAuditEvent,
  type ApiKeyListOptions,
  type ApiKeyDbInitResult,
  // Team Management
  initTeamDatabase,
  closeTeamDatabase,
  isTeamDbInitialized,
  createOrganization,
  getOrganization,
  getOrganizationByName,
  listOrganizations,
  updateOrganization,
  deleteOrganization,
  createTeam,
  getTeam,
  getTeamByName,
  listTeams,
  updateTeam,
  deleteTeam,
  addTeamMember,
  removeTeamMember,
  updateTeamMemberRole,
  getTeamMember,
  listTeamMembers,
  getUserTeamMemberships,
  isTeamMember,
  hasTeamRole,
  logTeamAudit,
  getTeamAuditEvents,
  cleanupExpiredMemberships,
  cleanupTeamAuditEvents,
  getTeamStats,
  // Team Management Types
  type TeamMemberRole,
  type TeamEventType,
  type Organization,
  type OrganizationSettings,
  type OrganizationWithStats,
  type Team,
  type TeamSettings,
  type TeamWithStats,
  type TeamMember,
  type TeamMembershipDetails,
  type CreateOrganizationOptions,
  type CreateTeamOptions,
  type AddTeamMemberOptions,
  type ListTeamsOptions,
  type ListTeamMembersOptions,
  type TeamAuditEvent,
  type TeamDbInitResult,
  type TeamStats,
  // Session Management
  initSessionDatabase,
  closeSessionDatabase,
  isSessionDbInitialized,
  getSessionConfig,
  updateSessionConfig,
  createSession,
  getSession,
  listSessions,
  revokeSession,
  revokeAllUserSessions,
  validateAccessToken,
  refreshTokens,
  blacklistToken,
  isTokenBlacklisted,
  getBlacklistedTokens,
  logSessionAudit,
  getSessionAuditEvents,
  cleanupExpiredSessionsMgmt,
  cleanupExpiredBlacklistEntries,
  cleanupSessionAuditEvents,
  getSessionStats,
  // Session Management Types
  type SessionEventType,
  type SessionDevice,
  type Session,
  type TokenClaims,
  type TokenPair,
  type CreateSessionOptions,
  type CreateSessionResult,
  type TokenValidationResult,
  type RefreshTokenResult,
  type SessionListOptions,
  type SessionAuditEvent,
  type SessionDbInitResult,
  type SessionStats,
  type BlacklistedToken,
  type SessionConfig,
  // Audit Trail
  initAuditDatabase,
  closeAuditDatabase,
  isAuditDbInitialized,
  getAuditConfig,
  updateAuditConfig,
  logAuditEvent,
  getAuditEvent,
  searchAuditEvents,
  getActionCategory,
  exportAuditLogs,
  verifyEventChecksum,
  verifyAuditIntegrity,
  addAuditEventListener,
  removeAuditEventListener,
  configureSiem,
  flushSiemQueue,
  getSiemQueueStatus,
  getAuditStats,
  aggregateAuditEvents,
  cleanupExpiredAuditEvents,
  cleanupFailedSiemQueue,
  // Audit Trail Types
  type AuditActorType,
  type AuditActionCategory,
  type AuditAction,
  type AuditResourceType,
  type AuditOutcome,
  type AuditActor,
  type AuditResource,
  type AuditContext,
  type AuditEvent,
  type CreateAuditEventOptions,
  type AuditSearchOptions,
  type AuditExportFormat,
  type AuditExportOptions,
  type AuditExportResult,
  type AuditSiemConfig,
  type AuditConfig,
  type AuditDbInitResult,
  type AuditStats,
  type AuditAggregateOptions,
  type AuditAggregateResult,
  // Executive Dashboard
  initDashboardDatabase,
  closeDashboardDatabase,
  isDashboardDbInitialized,
  getDashboardConfig,
  updateDashboardConfig,
  setAssetCriticality,
  getAssetCriticality,
  listAssetCriticalities,
  recordScan,
  getScanRecords,
  recordVulnerabilityDetected,
  markVulnerabilityRemediated,
  calculateHealthScore,
  getHealthScore,
  getVulnerabilityCounts,
  getScanCoverage,
  getMTTRMetrics,
  getTopRisks,
  getComplianceStatus,
  getDashboardSummary,
  saveDashboardSnapshot,
  getDashboardSnapshots,
  cleanupOldSnapshots,
  // Executive Dashboard Types
  type AssetCriticality,
  type TrendDirection,
  type DashboardTimeRange,
  type SeverityCounts,
  type TrendData,
  type ComplianceStatusSummary,
  type RiskSummary,
  type HealthScoreComponents,
  type HealthScore,
  type MTTRMetrics,
  type ScanCoverage,
  type DashboardSummary,
  type DashboardConfig,
  type DashboardSnapshot,
  type AssetCriticalityConfig,
  type DashboardDbInitResult,
  // Report Templates
  initReportDatabase,
  closeReportDatabase,
  isReportDbInitialized,
  createTemplate,
  getTemplate,
  getTemplateByName,
  listTemplates,
  updateTemplate,
  deleteTemplate,
  generateReport,
  createReportSchedule,
  getReportSchedule,
  listReportSchedules,
  updateReportSchedule,
  deleteReportSchedule,
  getReportHistory,
  cleanupReportHistory,
  // Report Templates Types
  type ReportFormat,
  type ReportScheduleFrequency,
  type BuiltinTemplateName,
  type ReportSectionType,
  type ReportSection,
  type ReportBranding,
  type ReportFilters,
  type ReportTemplate,
  type ReportGenerateOptions,
  type GeneratedReport,
  type ReportWebhook,
  type ReportSchedule,
  type ReportHistoryEntry,
  type CreateTemplateOptions,
  type CreateScheduleOptions,
  type ReportDbInitResult,
  // Trend Analysis
  initTrendDatabase,
  closeTrendDatabase,
  isTrendDbInitialized,
  recordTrendSnapshot,
  getVulnerabilityHistory,
  getTrendForecast,
  detectTrendAnomalies,
  compareTrendPeriods,
  listTrendTargets,
  cleanupTrendSnapshots,
  getTrendSnapshotCount,
  // Trend Analysis Types
  type TrendGranularity,
  type TrendDataPoint,
  type VulnerabilityHistory,
  type TrendForecast,
  type TrendForecastPoint,
  type TrendAnomaly,
  type AnomalyDetectionResult,
  type PeriodComparison,
  type MetricComparison,
  type TrendSnapshot,
  type GetHistoryOptions,
  type GetForecastOptions,
  type DetectAnomaliesOptions,
  type ComparePeriodOptions,
  type RecordSnapshotOptions,
  type TrendDbInitResult,
  // Risk Scoring
  initRiskDatabase,
  closeRiskDatabase,
  isRiskDbInitialized,
  getRiskConfig,
  updateRiskConfig,
  setRiskAssetConfig,
  getRiskAssetConfig,
  listRiskAssetConfigs,
  deleteRiskAssetConfig,
  calculateRiskScore,
  storeRiskScore,
  getStoredRiskScore,
  getPrioritizedList,
  clearRiskScores,
  getRiskStats,
  // Risk Scoring Types
  type RiskAssetCriticality,
  type RiskExposureLevel,
  type RiskTier,
  type RiskAssetConfig,
  type CvssComponents,
  type ExploitabilityFactors,
  type RiskScore,
  type CalculateRiskOptions,
  type RiskWeights,
  type PrioritizedVulnerability,
  type GetPrioritizedListOptions,
  type PrioritizedListResult,
  type RiskDbInitResult,
  type SetAssetCriticalityOptions,
  type RiskConfig,
  // Report Export (PDF, Excel, CSV)
  exportToPdf,
  exportToExcel,
  exportToCsv,
  exportReportToPdf,
  exportReportToExcel,
  exportVulnerabilitiesToCsv,
  createVulnerabilityWorksheet,
  createSummaryWorksheet,
  createComplianceWorksheet,
  checkExportDependencies,
  // Report Export Types
  type PdfPageSize,
  type PdfOrientation,
  type ExportFormat,
  type PdfHeaderFooter,
  type PdfBranding,
  type PdfExportOptions,
  type ExcelWorksheet,
  type ExcelColumn,
  type ExcelExportOptions,
  type CsvExportOptions,
  type ExportResult,
  type ReportData,
  type PdfExportResult,
  type ExcelExportResult,
  // Comparison
  initComparisonDb,
  closeComparisonDb,
  getComparisonDbPath,
  compareProjects,
  compareTeams,
  compareToBaseline,
  createBaseline,
  getBaseline,
  getDefaultBaseline,
  listBaselines,
  deleteBaseline,
  setDefaultBaseline,
  recordEntityMetrics,
  getRankings,
  getCachedComparison,
  cacheComparison,
  clearExpiredCache,
  // Comparison Types
  type ComparisonEntityType,
  type ComparisonMetric,
  type ComparisonTrend,
  type EntityMetrics,
  type ComparisonMetricResult,
  type ComparisonResult,
  type Baseline,
  type CreateBaselineOptions,
  type CompareProjectsOptions,
  type CompareTeamsOptions,
  type CompareToBaselineOptions,
  type RankingEntry,
  type GetRankingsOptions,
  type RankingsResult,
  type ComparisonDbInitResult,
  type ListBaselinesOptions,
  // PR Generator
  generateBranchName,
  generateCommitMessage,
  generatePrTitle,
  generatePrBody,
  createPullRequest,
  createBatchPullRequests,
  getPrStatus,
  type PrCreateOptions,
  type PrCreateResult,
  type BatchPrResult,
  type PrStatus,
  // IDE Integration
  DiagnosticSeverity,
  generateDiagnostics,
  generateCodeActions,
  generateFixEdit,
  applyFixes,
  type Position,
  type Range,
  type Diagnostic,
  type DiagnosticRelatedInformation,
  type CodeAction,
  type WorkspaceEdit,
  type TextEdit,
  type Command,
  type IdeDiagnosticsResult,
  type IdeCodeActionsResult,
  // Dependency Updater
  getUpdateType,
  isBreakingUpdate,
  detectProjectPackageManager,
  checkUpdates,
  previewUpdate,
  applyUpdate,
  applyUpdates,
  rollbackUpdates,
  type AvailableUpdate,
  type UpdateCheckResult,
  type UpdatePreview,
  type UpdateApplyResult,
  type BatchUpdateResult,
  // Fix Verification
  extractVulnerabilities,
  findVulnerability,
  verifySingleFix,
  verifyFixes,
  compareScanResultsForVerification,
  generateVerificationSummary,
  isCvePresent,
  getAllCveIds,
  countBySeverity,
  calculateFixRate,
  type VulnVerificationResult,
  type FixVerificationResult,
  type RescanOptions,
  // SLA Tracking
  initSlaDatabase,
  closeSlaDatabase,
  configureSla,
  getSlaConfig,
  getDefaultSlaConfig,
  listSlaConfigs,
  deleteSlaConfig,
  trackVulnerability,
  acknowledgeVulnerability,
  remediateVulnerability,
  getSlaStatus,
  getSlaBreaches,
  clearTrackedVulnerabilities,
  type SlaSeverity,
  type SlaTarget,
  type SlaConfig,
  type SlaConfigureOptions,
  type VulnSlaStatus,
  type SlaStatusSummary,
  type SlaGetStatusOptions,
  type SlaStatusResult,
  type SlaBreach,
  type SlaApproaching,
  type SlaBreachesResult,
  type SlaGetBreachesOptions,
} from "@cicd/shared";
