// Re-export everything from the shared library
export {
  // Config
  config,
  type Config,
  // Validation
  validateSeverity,
  sanitizePath,
  sanitizeImageName,
  // HTTP helpers
  fetchJson,
  basicAuth,
  // Trivy
  trivyScanPath,
  trivyScanImage,
  trivyGenerateSbom,
  trivyGenerateSbomImage,
  trivyScanIac,
  trivyScanSecrets,
  trivyScanSecretsImage,
  trivyScanLicenses,
  trivyScanLicensesImage,
  trivyScanImageFull,
  trivyScanPathFull,
  // SonarQube
  sonarGetProjects,
  sonarGetIssues,
  sonarGetSecurityHotspots,
  sonarGetMetrics,
  // Dependency-Track
  dtrackGetProjects,
  dtrackGetVulnerabilities,
  dtrackGetFindings,
  dtrackGetComponents,
  uploadSbomToDtrack,
  // Gitea
  giteaGetRepos,
  giteaGetRepo,
  giteaGetBranches,
  giteaGetCommits,
  giteaCreateRepo,
  giteaMigrateRepo,
  // Drone
  droneGetRepos,
  droneGetBuilds,
  droneGetBuild,
  droneGetBuildLogs,
  droneTriggerBuild,
  // Registry
  registryGetCatalog,
  registryGetTags,
  // Combined
  securityScanAll,
  checkPlatformStatus,
  // Security Dashboard
  getSecurityDashboard,
  // Registry Scanner
  listRegistryImages,
  scanRegistry,
  // Multi-Registry
  detectRegistryType,
  configureRegistry,
  getRegistryConfig,
  listRegistryConfigs,
  removeRegistryConfig,
  getDefaultRegistry,
  clearRegistryConfigs,
  getRegistryAuth,
  scanMultipleRegistries,
  testRegistryConnection,
  // SARIF
  trivyToSarif,
  sonarToSarif,
  dtrackToSarif,
  dashboardToSarif,
  mergeSarifLogs,
  sarifToJson,
  getSarifSummary,
  uploadSarifToGitHub,
  writeSarifFile,
  // Scheduler
  parseCronExpression,
  validateCronExpression,
  describeCronExpression,
  getNextRunTime,
  getNextRunTimes,
  createSchedule,
  getSchedule,
  listSchedules,
  updateSchedule,
  deleteSchedule,
  triggerSchedule,
  getScheduleHistory,
  startScheduler,
  stopScheduler,
  saveSchedulesToFile,
  loadSchedulesFromFile,
  clearAllSchedules,
  // Remediation
  generateRemediations,
  getRemediationSummary,
  formatRemediationAsMarkdown,
  getHighPriorityRemediations,
  getSafeRemediations,
  // Compliance
  COMPLIANCE_CONTROLS,
  getComplianceFrameworks,
  getComplianceControls,
  getComplianceControl,
  mapFindingToControls,
  generateComplianceReport,
  generateComplianceHtml,
  recordComplianceTrend,
  getComplianceTrend,
  clearComplianceTrends,
  getComplianceTrendTargets,
  checkComplianceStatus,
  // OPA/Rego
  BUILTIN_POLICIES,
  listBuiltinPolicies,
  getBuiltinPolicy,
  getBuiltinPolicyInfo,
  validateRegoSyntax,
  evaluateOpaPolicy,
  evaluateMultiplePolicies,
  scanResultsToOpaInput,
  trivyResultToOpaInput,
  dashboardResultToOpaInput,
  createOpaInput,
  // Vulnerability Database
  initVulnDatabase,
  closeVulnDatabase,
  isVulnDbInitialized,
  lookupVulnerability,
  searchVulnerabilities,
  getVulnDbStats,
  annotateVulnerability,
  getVulnAnnotation,
  // Database Sync
  getTrivyDbStatus,
  downloadTrivyDb,
  syncVulnDatabase,
  getVulnDbSyncStatus,
  isOfflineScanAvailable,
  // Offline Scanner
  offlineScanImage,
  offlineScanPath,
  getOfflineScanCapabilities,
  // Redis Cache
  getRedisConfig,
  getTTLConfig,
  initRedisConnection,
  closeRedisConnection,
  isRedisConnected,
  initDistributedCaches,
  getAllCacheStats,
  clearAllCaches,
  invalidateCacheByPattern,
  getCacheHealth,
  type RedisConfig,
  type CacheStats,
  type CacheTTLConfig,
  type CacheHealthStatus,
  // Suppression Database
  initSuppressionDatabase,
  closeSuppressionDatabase,
  isSuppressionDbInitialized,
  createDbSuppression,
  getDbSuppression,
  listDbSuppressions,
  updateDbSuppression,
  deleteDbSuppression,
  logSuppressionApplication,
  getSuppressionAuditLog,
  getSuppressionDbStats,
  applyDbSuppressions,
  importSuppressionsToDb,
  exportSuppressionsFromDb,
  markExpiredSuppressions,
  type SuppressionStatus,
  type SuppressionAuditAction,
  type SuppressionAuditEntry,
  type SuppressionListOptions,
  type SuppressionDbStats,
  // Prometheus Metrics
  METRICS,
  metricsCollector,
  toPrometheusFormat,
  getMetrics,
  pushToGateway,
  deleteFromGateway,
  recordScanMetrics,
  recordCacheHit,
  recordCacheMiss,
  recordCircuitBreakerFailure,
  resetMetrics,
  getMetricsSnapshot,
  type MetricsSnapshot,
  type ScanMetrics,
  type PushgatewayConfig,
  type PushgatewayResult,
  // Scan Comparison
  extractTrivyVulnerabilities,
  compareTrivyScans,
  getScanHistory,
  resetScanHistory,
  storeTrivyScan,
  compareWithPrevious,
  storeAndCompare,
  type ScanDiffResult,
  type StoredScanRecord,
  type ScanCompareOptions,
  // SSO Configuration
  initSsoDatabase,
  closeSsoDatabase,
  isSsoDbInitialized,
  configureSamlProvider,
  configureOidcProvider,
  getSsoProvider,
  listSsoProviders,
  deleteSsoProvider,
  setSsoProviderEnabled,
  createSsoSession,
  getSsoSession,
  validateSsoSession,
  terminateSsoSession,
  terminateAllUserSessions,
  listUserSessions,
  listAllSessions,
  cleanupExpiredSessions,
  getSsoAuditEvents,
  // SSO SAML
  generateSpMetadata,
  validateSamlAssertion,
  generateSamlLogoutRequest,
  // SSO OIDC
  validateOidcToken,
  validateOidcTokenByIssuer,
  refreshOidcToken,
  getOidcUserInfo,
  // SSO Types
  type SsoProviderType,
  type SamlProviderConfig,
  type OidcProviderConfig,
  type SsoSession,
  type SsoValidationResult,
  type SsoMetadataResult,
  type SsoAuditEvent,
  type SsoDbInitResult,
  type SsoProviderSummary,
  // RBAC
  initRbacDatabase,
  closeRbacDatabase,
  isRbacDbInitialized,
  createRole,
  getRole,
  getRoleByName,
  listRoles,
  updateRole,
  deleteRole,
  listPermissions,
  grantPermissionToRole,
  revokePermissionFromRole,
  getRolePermissions,
  assignRoleToUser,
  unassignRoleFromUser,
  getUserRoles,
  checkPermission,
  listUserPermissions,
  isUserAdmin,
  getRbacAuditEvents,
  // RBAC Types
  type RbacRole,
  type RbacPermission,
  type RbacUserRole,
  type RbacCheckResult,
  type RbacAuditEvent,
  type RbacRoleWithPermissions,
  type RbacDbInitResult,
  // API Key Management
  VALID_SCOPES,
  initApiKeyDatabase,
  closeApiKeyDatabase,
  isApiKeyDbInitialized,
  createApiKey,
  getApiKey,
  listApiKeys,
  revokeApiKey,
  rotateApiKey,
  validateApiKey,
  getApiKeyAuditEvents,
  markExpiredApiKeys,
  getApiKeyStats,
  cleanupApiKeyAuditLogs,
  // API Key Types
  type ApiKeyScope,
  type ApiKeyEventType,
  type ApiKeyStatus,
  type ApiKey,
  type ApiKeyCreateOptions,
  type ApiKeyCreateResult,
  type ApiKeyDisplay,
  type ApiKeyValidationResult,
  type ApiKeyRotateResult,
  type ApiKeyAuditEvent,
  type ApiKeyListOptions,
  type ApiKeyDbInitResult,
  // Team Management
  initTeamDatabase,
  closeTeamDatabase,
  isTeamDbInitialized,
  createOrganization,
  getOrganization,
  getOrganizationByName,
  listOrganizations,
  updateOrganization,
  deleteOrganization,
  createTeam,
  getTeam,
  getTeamByName,
  listTeams,
  updateTeam,
  deleteTeam,
  addTeamMember,
  removeTeamMember,
  updateTeamMemberRole,
  getTeamMember,
  listTeamMembers,
  getUserTeamMemberships,
  isTeamMember,
  hasTeamRole,
  logTeamAudit,
  getTeamAuditEvents,
  cleanupExpiredMemberships,
  cleanupTeamAuditEvents,
  getTeamStats,
  // Team Management Types
  type TeamMemberRole,
  type TeamEventType,
  type Organization,
  type OrganizationSettings,
  type OrganizationWithStats,
  type Team,
  type TeamSettings,
  type TeamWithStats,
  type TeamMember,
  type TeamMembershipDetails,
  type CreateOrganizationOptions,
  type CreateTeamOptions,
  type AddTeamMemberOptions,
  type ListTeamsOptions,
  type ListTeamMembersOptions,
  type TeamAuditEvent,
  type TeamDbInitResult,
  type TeamStats,
  // Session Management
  initSessionDatabase,
  closeSessionDatabase,
  isSessionDbInitialized,
  getSessionConfig,
  updateSessionConfig,
  createSession,
  getSession,
  listSessions,
  revokeSession,
  revokeAllUserSessions,
  validateAccessToken,
  refreshTokens,
  blacklistToken,
  isTokenBlacklisted,
  getBlacklistedTokens,
  logSessionAudit,
  getSessionAuditEvents,
  cleanupExpiredSessionsMgmt,
  cleanupExpiredBlacklistEntries,
  cleanupSessionAuditEvents,
  getSessionStats,
  // Session Management Types
  type SessionEventType,
  type SessionDevice,
  type Session,
  type TokenClaims,
  type TokenPair,
  type CreateSessionOptions,
  type CreateSessionResult,
  type TokenValidationResult,
  type RefreshTokenResult,
  type SessionListOptions,
  type SessionAuditEvent,
  type SessionDbInitResult,
  type SessionStats,
  type BlacklistedToken,
  type SessionConfig,
  // Audit Trail
  initAuditDatabase,
  closeAuditDatabase,
  isAuditDbInitialized,
  getAuditConfig,
  updateAuditConfig,
  logAuditEvent,
  getAuditEvent,
  searchAuditEvents,
  getActionCategory,
  exportAuditLogs,
  verifyEventChecksum,
  verifyAuditIntegrity,
  addAuditEventListener,
  removeAuditEventListener,
  configureSiem,
  flushSiemQueue,
  getSiemQueueStatus,
  getAuditStats,
  aggregateAuditEvents,
  cleanupExpiredAuditEvents,
  cleanupFailedSiemQueue,
  // Audit Trail Types
  type AuditActorType,
  type AuditActionCategory,
  type AuditAction,
  type AuditResourceType,
  type AuditOutcome,
  type AuditActor,
  type AuditResource,
  type AuditContext,
  type AuditEvent,
  type CreateAuditEventOptions,
  type AuditSearchOptions,
  type AuditExportFormat,
  type AuditExportOptions,
  type AuditExportResult,
  type AuditSiemConfig,
  type AuditConfig,
  type AuditDbInitResult,
  type AuditStats,
  type AuditAggregateOptions,
  type AuditAggregateResult,
} from "@cicd/shared";
