// Re-export everything from the shared library
export {
  // Config
  config,
  type Config,
  // Validation
  validateSeverity,
  sanitizePath,
  sanitizeImageName,
  // HTTP helpers
  fetchJson,
  basicAuth,
  // Trivy
  trivyScanPath,
  trivyScanImage,
  trivyGenerateSbom,
  trivyGenerateSbomImage,
  trivyScanIac,
  trivyScanSecrets,
  trivyScanSecretsImage,
  trivyScanLicenses,
  trivyScanLicensesImage,
  trivyScanImageFull,
  trivyScanPathFull,
  // SonarQube
  sonarGetProjects,
  sonarGetIssues,
  sonarGetSecurityHotspots,
  sonarGetMetrics,
  // Dependency-Track
  dtrackGetProjects,
  dtrackGetVulnerabilities,
  dtrackGetFindings,
  dtrackGetComponents,
  uploadSbomToDtrack,
  // Gitea
  giteaGetRepos,
  giteaGetRepo,
  giteaGetBranches,
  giteaGetCommits,
  giteaCreateRepo,
  giteaMigrateRepo,
  // Drone
  droneGetRepos,
  droneGetBuilds,
  droneGetBuild,
  droneGetBuildLogs,
  droneTriggerBuild,
  // Registry
  registryGetCatalog,
  registryGetTags,
  // Combined
  securityScanAll,
  checkPlatformStatus,
  // Security Dashboard
  getSecurityDashboard,
  // Registry Scanner
  listRegistryImages,
  scanRegistry,
  // Multi-Registry
  detectRegistryType,
  configureRegistry,
  getRegistryConfig,
  listRegistryConfigs,
  removeRegistryConfig,
  getDefaultRegistry,
  clearRegistryConfigs,
  getRegistryAuth,
  scanMultipleRegistries,
  testRegistryConnection,
  // SARIF
  trivyToSarif,
  sonarToSarif,
  dtrackToSarif,
  dashboardToSarif,
  mergeSarifLogs,
  sarifToJson,
  getSarifSummary,
  uploadSarifToGitHub,
  writeSarifFile,
  // Scheduler
  parseCronExpression,
  validateCronExpression,
  describeCronExpression,
  getNextRunTime,
  getNextRunTimes,
  createSchedule,
  getSchedule,
  listSchedules,
  updateSchedule,
  deleteSchedule,
  triggerSchedule,
  getScheduleHistory,
  startScheduler,
  stopScheduler,
  saveSchedulesToFile,
  loadSchedulesFromFile,
  clearAllSchedules,
  // Remediation
  generateRemediations,
  getRemediationSummary,
  formatRemediationAsMarkdown,
  getHighPriorityRemediations,
  getSafeRemediations,
  // Compliance
  COMPLIANCE_CONTROLS,
  getComplianceFrameworks,
  getComplianceControls,
  getComplianceControl,
  mapFindingToControls,
  generateComplianceReport,
  generateComplianceHtml,
  recordComplianceTrend,
  getComplianceTrend,
  clearComplianceTrends,
  getComplianceTrendTargets,
  checkComplianceStatus,
} from "@cicd/shared";
